USE my_emp;

-- Q1) EMP 테이블의 구조와 데이터를 복사하여 TEST_EMP 테이블을 생성하자.
DROP TABLE IF EXISTS TEST_EMP;
CREATE TABLE TEST_EMP AS SELECT * FROM EMP;
CREATE TABLE TEST_DEPT AS SELECT * FROM DEPT;

-- Q2) TEST_EMP 테이블에 기본 키(PK) 제약 조건을 EMPNO 컬럼에 추가하자.
ALTER TABLE TEST_EMP
ADD CONSTRAINT PK_TEST_EMP PRIMARY KEY (EMPNO);

-- Q3) TEST_EMP 테이블에 유니크 키(UNIQUE) 제약 조건을 ENAME 컬럼에 추가하자.
ALTER TABLE TEST_EMP
ADD CONSTRAINT UQ_TEST_EMP_ENAME UNIQUE (ENAME);

-- Q4) SAL > 0 조건의 체크 제약 조건을 추가하자.
UPDATE TEST_EMP SET SAL = 1000 WHERE SAL <= 0;
ALTER TABLE TEST_EMP
ADD CONSTRAINT CHK_SAL_POSITIVE CHECK (SAL > 0);

-- Q5) 외래 키(FK): DEPTNO → TEST_DEPT(DEPTNO) 참조하도록 추가하자.
ALTER TABLE TEST_EMP
ADD CONSTRAINT FK_TEST_EMP_DEPT FOREIGN KEY (DEPTNO)
REFERENCES TEST_DEPT(DEPTNO);

-- Q6) SAL > 0 체크 제약 조건 삭제
ALTER TABLE TEST_EMP
DROP CHECK CHK_SAL_POSITIVE;

-- Q7) SAL >= 1000 조건으로 다시 체크 제약 조건 추가
ALTER TABLE TEST_EMP
ADD CONSTRAINT CHK_SAL_MIN CHECK (SAL >= 1000);

-- Q8) TEST_EMP 테이블에서 기본 키 제약 조건을 삭제하자.
ALTER TABLE TEST_EMP DROP PRIMARY KEY;

-- Q9) TEST_EMP 테이블에서 유니크 키 제약 조건을 삭제하자.
ALTER TABLE TEST_EMP DROP INDEX UQ_TEST_EMP_ENAME;

-- Q10) TEST_EMP 테이블에서 외래 키 제약 조건을 삭제하자.
ALTER TABLE TEST_EMP DROP FOREIGN KEY FK_TEST_EMP_DEPT;

-- Q11) TEST_EMP 제약조건 확인
SELECT * 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'TEST_EMP';

-- Q12) DEPT 테이블의 구조와 데이터를 복사하여 TEST_DEPT 테이블을 생성하자.
DROP TABLE IF EXISTS TEST_DEPT;
CREATE TABLE TEST_DEPT AS SELECT * FROM DEPT;

-- Q13) TEST_DEPT 테이블에 기본 키(PK) 제약 조건을 DEPTNO 컬럼에 추가하자.
ALTER TABLE TEST_DEPT
ADD CONSTRAINT PK_TEST_DEPT PRIMARY KEY (DEPTNO);

-- Q14) TEST_DEPT 테이블에 유니크 키(UNIQUE) 제약 조건을 DNAME 컬럼에 추가하자.
ALTER TABLE TEST_DEPT
ADD CONSTRAINT UQ_TEST_DEPT_DNAME UNIQUE (DNAME);

-- Q15) LOC 값이 특정 값들만 허용되도록 CHECK 제약 조건 추가
ALTER TABLE TEST_DEPT
ADD CONSTRAINT CHK_LOC_VALUES CHECK (LOC IN ('NEW YORK', 'DALLAS', 'CHICAGO'));

-- Q16) CHECK 제약 조건 삭제 후, 빈 문자열만 제한하는 조건으로 다시 추가하자.
ALTER TABLE TEST_DEPT DROP CHECK CHK_LOC_VALUES;
ALTER TABLE TEST_DEPT
ADD CONSTRAINT CHK_LOC_NOT_EMPTY CHECK (LOC != '');

-- Q17) TEST_DEPT 테이블의 모든 제약 조건 삭제
ALTER TABLE TEST_DEPT DROP PRIMARY KEY;
ALTER TABLE TEST_DEPT DROP INDEX UQ_TEST_DEPT_DNAME;
ALTER TABLE TEST_DEPT DROP CHECK CHK_LOC_NOT_EMPTY;

-- Q18) TEST_DEPT 제약조건 확인
SELECT * 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'TEST_DEPT';