CREATE DEFINER=`mydb`@`%` PROCEDURE `01_GetEmp_Res`()
BEGIN
WITH RECURSIVE EMP_RES AS (
	-- [1] 최상위 정보를 출력해보자
	SELECT EMPNO, ENAME, MGR, 1 AS LEVEL
	FROM EMP
	WHERE MGR IS NULL
	UNION ALL
	-- [2] 각 사원의 부하직원을 재귀적으로 출력하자
	SELECT E.EMPNO, E.ENAME, E.MGR, ET.LEVEL + 1
	FROM EMP E JOIN EMP_RES ET ON E.MGR = ET.EMPNO
	)
	SELECT * FROM EMP_RES;
END