CREATE DEFINER=`mydb`@`%` PROCEDURE `02_GuGuDan`()
BEGIN
-- Q15. 구구단 중 3단을 출력해보자
	WITH RECURSIVE GuGuDan AS (
	SELECT 3 AS DAN, 1 AS NUM, 3*1 AS RESULT

	UNION ALL

	SELECT DAN, NUM+1, DAN*(NUM+1)
	FROM GuGuDan
	WHERE NUM < 9
	)
	SELECT * FROM GuGuDan;
END