CREATE DEFINER=`mydb`@`%` PROCEDURE `04_Fibo`()
BEGIN
	WITH RECURSIVE Fibo AS (
	-- [1] 초기값
	SELECT 0 AS N, 0 AS FIB, 1 AS PREV_FIBO
	UNION ALL
	-- [2] 재귀적으로 계산
	SELECT N+1, PREV_FIBO AS FIB, FIB + PREV_FIBO AS PREV_FIBO
	FROM Fibo
	WHERE N < 10 -- 반복문 무한으로 도는거 방지
	)
	SELECT * FROM Fibo;
END